### PR TITLE
Add a publish button on article view.

### PR DESCRIPTION
**Pull request by Bonbadil**
Only visible with and only work for TinyTinyRss (the one I use).
Oh, and I had no clue which symbol use on the button, so I just put "P" to Publish and "U" to Unpublished. Any idea, someone?

### CODE REVIEW

**Comment by jeena** [comment]
Hm what about the cloud with the arrow for published and the one without for unpublished?

**Comment by jeena** [comment]
I've been thinking, perhaps we should use the apple share button &#59157 or even better the android one &#59196 and work with color or even opacity to show if it is published or unpublished?

**Comment by Bonbadil** [comment]
I think using the opacity could be more intuitive, but then shouldn't do the same to the other icons, too ?
EDIT: And in this case, I would like using the RSS icon.

**Comment by jeena** [comment]
I kind of like the favourite star to be empty in the middle but it still could be opacity 50% or something, that is true. And I never liked the "read/unread" solution anyway so perhaps we could use a different icon for that too, for example the open book?
EDIT: Will people who use TTRSS and this feature understand what the RSS icon stands for? The share buttons are known for users of iOS and Android I don't think there is a share button for Firefox OS yet?

**Comment by Bonbadil** [comment]
Yes, the cross is not great, but the check mark and opacity could do the trick...
Why this is so difficult? :-)

**Comment by jeena** [comment]
Yeah you're probably right. It is difficult because icons are not really universally understandable ^^

**Comment by Bonbadil** [comment]
The icons change could be another Pull Request. Do you agree on this one?

**Pull request merged**
