### PR TITLE
Starred

### PR DESCRIPTION
**Pull request by Alvarord**
Small button to put a star in the article.

I'm newbie in github forking, javascript, etc so in advance excuse all the errors. 

I think is a nice funcionality to have, and I'm sure that it can be improve. Maybe it can be possible to put in the circle a yellow for the starred articles too.

Thanks in advance

### CODE REVIEW

**Comment by jeena** [comment]
This is really great, thank you so much, I will do some minor changes to the naming but otherwise it is perfect. Actually I've been thinking about implementing it myself because sometimes I wanted to read a longer article on my desktop but had no possibility to send it to my desktop computer. This solves this problem, so thank you, I will test it and then it will make it hopefully soon to the Marketplace version.

**Comment by Alvarord** [comment]
I had the same problem. And I just wanted it to read it later too ;)

I suppose that there are some improvements that because this is my first time with JavaScript I don't know how to solve, for example put a "_" with different color, instead of "_" and "no *"

**Comment by jeena** [comment]
Yeah that is a good idea to use a different color. I will add a "starred" class to it and give it a different color in CSS, no problem.

**Comment by jeena** [comment]
I changed my mind and I used a icon set which has a full and a empty star instead.

**Comment by Alvarord** [comment]
Much more better. The truth is that I didn't know how to add it

**Pull request merged**
