### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by jancborchardt**
- correct capitalization of »ownCloud«
- read items get subdued text and arrow color
- restrict article titles to one line to not give more importance to articles with long titles
- remove unsemantic strong tag from feed title
- reduce opacity of feed title and excerpt to focus on article title
- reorder settings for info bubbles and log out to the bottom
- give feedback on selected input field

### CODE REVIEW

**Comment by jeena** [comment]
I like the changes, but I'd like to know why you think that the strong tag for the feed title is unsemantic. The title is more then just a paragraph but not really a headline. Or perhaps it even is a headline, actually in theory h1 could be appropriate.

**Comment by jeena** [comment]
There is a serious problem with https://github.com/jancborchardt/FeedMonkey/commit/54ebe5d0570f55dd7578e7d56488307e707d2dc3 I'm not really blind or anything but even I can't read the text if it has the deep red color anymore.

Another thing is that the opacity thing makes the text kind of soft, not that crispy anymore, I think I will change it and use a darker white or something so it wouldn't need to use opacity but still be darker.

**Comment by jeena** [comment]
Also the restriction for only one line for the title is a bit problematic because people like to skim over the titles in the list view to get a overview over. If not the whole title is visible then it can be very difficult to decide if you want to read the article or not.

**Comment by jancborchardt** [comment]
@jeena ok, then there probably needs to be another hue for all the colors for when the items are read. I prefer to use opacity for that because that makes it very flexible.

About the title – yeah, not sure about that. One thing is skimming titles, but normally titles have the useful info at the start, or are not that long anyway. If the whole title is shown, that gives more importance to entries which can’t choose concise titles.

**Pull request merged**
