### PR TITLE
Categories based application

### PR DESCRIPTION
**Pull request by markelarizaga**
I worked on making the app retrieve the categories from the server. With these changes the app entry point is the categories screen and the user can browse them until reaching the articles.
I did not think on caching the info etc, as this is the result of a first attemp, but anyway I hope this can be useful for somebody.

Great job with this project BTW

### CODE REVIEW

**Comment by jeena** [comment]
Cool! I will need to have a look at it if I can merge it, as far as I see it is only working with TTRSS yet, but it shouldn't be a big change to add it to ownCloud and Pond.

**Comment by markelarizaga** [comment]
Correct, I forgot to mention that. As I'm only using TT-RSS, I made changes
for it only, sorry about this.

Just to mention it again, there are probably things you don't like in the
implementation, even for me actually :) so look at it carefully before
deciding to merge. However I hope this can serve at least as a base for the
categories stuff.

**Comment by markelarizaga** [comment]
Hello again,
Seems there was some kind of problem when merging the code tot he repo. Probably the problem was the code itself, xD.
Just in case you are interested, I have been working on reimplementing the application using AngularJS. I based my work on your repo but it has changed a lot already to the point of being a completely different app.
Regards!

**Comment by jeena** [comment]
Yeah I think the problem that it is only a fix for TTRSS will make it impossible to merge. And yeah sure I am interested in seeing it, do you have a URL? Actually I had a look at Angular before starting implementing this but gave up because it was so very different from what I usually do in JavaScript.

**Comment by markelarizaga** [comment]
Sorry I forgot to send the URL of the fork:
https://github.com/markelarizaga/FeedMonkey

Checkout the branch called angular.

As I was only interested on TT-RSS I did not implement any other backend,
but I think it should be quite easy to add new ones.
In case you have any question regarding the code just ask me.

Regards,
Markel

**Pull request closed without merging**
